URL = "https://app.thegaas.com/"
USER_NAME = "vivetha+test1@dgraph.io"
PASSWORD = "Password@123"
BACKEND_NAME = "Test Backend"
BACKEND_ZONE = "stgdgraph"
ORGANIZATION = "Org2"
NEW_ORGANIZATION = "org"
BACKEND_MONITORING_TIMEOUT = 50
ORGANIZATION_NAME = "Org2"
USER_NAME_2 = "vivetha+test2@dgraph.io"
FIELD_NAMES = ["name"]
CLOUD_PROVIDER = "enterprise"
SCHEMA1 = "type User  {  id: ID!   name: String }"
SCHEMA2 = "type User  {  id: ID!   name: String   age: Int }"
QUERY_RESULT = {'queryUser': []}
QUERY_RESULT1 = {'queryUser': [{"name": "santhosh"}]}
QUERY_RESULT2 = {'queryUser': [{'name': 'santhosh'}, {'name': 'user1'}]}
TOTAL_AMOUNT =  "TOTAL AMOUNT $0 COUPON NA"
BILLING_DESCRIPTION = "Description Slash GraphQL Backends (0 Backends) Slash GraphQL Data Transfer (0.000 GB) Slash GraphQL Included Data Transfer (0GB for 0 Backends)"   
BILLING_AMOUNT = "Amount $0.00 $0.00 $0.00"
BROWSER_NAME = "headlesschrome"
MUTATION_RESULT = {'addUser': {'numUids': 1}}