URL = "https://app.thegaas.com/"
USER_NAME = "vivetha+test1@dgraph.io"
PASSWORD = "Password@123"
BACKEND_NAME = "Test Backend"
BACKEND_ZONE = "stgdgraph"
ORGANIZATION = "Org2"
NEW_ORGANIZATION = "org"
BACKEND_MONITORING_TIMEOUT = 50
ORGANIZATION_NAME = "Org2"
USER_NAME_2 = "vivetha+test2@dgraph.io"
FIELD_NAMES = ["name", "id"]