URL = "https://app.thegaas.com/"
USER_NAME = "vivetha+test1@dgraph.io"
PASSWORD = "Password@123"
BACKEND_NAME = "Test Backend"
BACKEND_ZONE = "stgdgraph"
ORGANIZATION = "Org2"
NEW_ORGANIZATION = "org"
BACKEND_MONITORING_TIMEOUT = 50
ORGANIZATION_NAME = "Org2"
USER_NAME_2 = "vivetha+test2@dgraph.io"
FIELD_NAMES = ["name"]
CLOUD_PROVIDER = "enterprise"
SCHEMA1 = "type User  {  id: ID!   name: String }"
SCHEMA2 = "type User  {  id: ID!   name: String   age: Int }"
QUERY_RESULT = {'queryUser': []}
QUERY_RESULT1 = {'queryUser': [{"name": "santhosh"}]}
QUERY_RESULT2 = {'queryUser': [{'name': 'santhosh'}, {'name': 'user1'}]}
SCHEMA3 = "type Task  @auth(query: { rule: \"query($USER: String!) { queryTask { user(filter: { username: { eq: $USER } }) {  __typename } } }\"}) {  id: ID!   title: String   user: User }type User  {  username: ID!   name: String }"
RULES = "query($USER: String!) { queryTask { user(filter: { username: { eq: $USER } }) {  __typename } } }"