URL = "https://api.stage.thegaas.com/"
BACKEND_NAME = "Test"
BACKEND_ZONE = "stgdgraph"
HEADERS = { "Authorization" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1ETXlNemcyTnpFME1qTkNORUUzTWpZME1UVTJNa0pCTVRjMFFUUkVPVEJFT0VZNE5UWXhSUSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kZ3JhcGgtc2Fhcy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDEyNDU5MjU2NzI2NjQzMDk0MTAiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDcwIiwiaHR0cHM6Ly9kZXYtZGdyYXBoLXNhYXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxNTU0MjYxOSwiZXhwIjoxNjE1NjI5MDE5LCJhenAiOiJnYnBWcTdpMWdNdmdtdEkzbXVBem9aSEpiVTJieDVqdCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.hxmoZyr2sW8I-PUXE3cKZ5rJ_DBKBfU3wS4TbBLbjhcTsSkAh44_KWGnC1gHm_tAQTgwbhhn9AL26YGsY2khjSW7OhMZljnaE3Rrl1j4euxJeMNqkk_Sc4H-ex-U4YKToIHtagK_i1oMBeFfpg-F5miWPVkHV8lP2fXrJPQsnorSseljYbGy2-jFt09fweICXvxzNiwKUetcMUUGYLC0-nCbUfeTaJgGYpf-dXrvzIgpItgUAlwRjELwEmbtZT8uNjPM7KaK3Ig-y526iPUk-_uJfQ61aSAKtUbZMBiVWgkHyFvJCdUnJw_NkEXLtfifWh0M6sFA7k9ntLDcQ2uXgQ",
            "Content-Type" : "application/json" }
USER2_HEADER = { "Authorization" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1ETXlNemcyTnpFME1qTkNORUUzTWpZME1UVTJNa0pCTVRjMFFUUkVPVEJFT0VZNE5UWXhSUSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kZ3JhcGgtc2Fhcy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjAyNTMzZmI3YzBkZmYwMDcwZDI5ZmY3IiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA3MCIsImh0dHBzOi8vZGV2LWRncmFwaC1zYWFzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MTU1NDg1MDksImV4cCI6MTYxNTYzNDkwOSwiYXpwIjoiZ2JwVnE3aTFnTXZnbXRJM211QXpvWkhKYlUyYng1anQiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.ieOLxCa9N88rP9vtsLfKUlZyvY-NbK6WcnhlEEYqoo692LgmudiCo3pGQ7ysQ3jRitH0wh7-k8w3k8v1dJ9ZsZHH90-xfJYG1UwePqmUFKPpqtx_S8HwzD95iMrEeogWa9jcVhyXssy64d6d_wJJeV0qdXiTmJLUJu147TDAwEcp-t7pfLDY3E6vez81w6SJFkSz4TumTdkeBZIQyUv2S4eJPy2Laiv9KDSAMn45WbVMXHGgdDkeUQtB08jXWihKgWg2A327jDoU2niAmddR0cY0h2z1PCn12qHNklaHs-f4gUPqGTskPxiYOl7M32hDChIADs2EdaB8UA5fL8EmKQ",
            "Content-Type" : "application/json" }
DELETE_API_KEY_MESSAGE = "API Key Deleted Successfully."
SCHEMA = "type Task { id: ID! title: String! @search(by: [fulltext]) completed: Boolean! @search  user: User! }type User { username: String! @id @search(by: [hash]) name: String @search(by: [exact]) tasks: [Task] @hasInverse(field: user) }"
MUTATION_QUERY_1 = """{\"query\":\"mutation AddTasks {\\n addTask(input: [\\n {title: \\\"Create a database\\\", completed: false, user: {username: \\\"your-email@example.com\\\"}}]) {\\n numUids\\n task {\\n title\\n user {\\n username\\n }\\n  }\\n  }\\n}\"}"""
QUERY = """{\"query\":\"query {\\n \ __schema {\\n \ \ \ __typename\\n \ }\\n}\"}"""
INTROSPECTION_QUERY = """{"query":"query {__schema { __typename }}"}"""
NO_SCHEMA_ERROR = "Not resolving __schema. There's no GraphQL schema in Dgraph.  Use the /admin API to add a GraphQL schema"