# This is a basic workflow to help you get started with Actions

name: DOCKER

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        dgraphBranch:
          description: 'Dgraph Docker Branch'     
          required: true
          default: 'v21.03.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    timeout-minutes:  4000

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          path: Automation_workspace
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8.7 # optional, default is 3.x
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64 # optional
          # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
          token: ${{ github.token }} # optional, default is ${{ github.token }}
          
      - name: Install requirements for Dgraph and Slash
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/Automation_workspace/utilities
          ls -alh
          sudo python3 env_setup.py -l All -c enabled -o 20
      
      
      # Download Dgraph Repo
      - name: Check out Dgraph repo
        uses: actions/checkout@master
        with:
          repository: dgraph-io/dgraph
          ref: ${{ github.event.inputs.dgraphBranch }}
          clean: false  
          path: dgraph_workspace  
        
       
     # Check Config File for Dgraph
      -  name: Check dgraph execution configuration
         run: |
           echo ${{ github.workspace }}
           cd ${{ github.workspace }}/Automation_workspace
           cat conf/dgraph/conf_dgraph.json
         
      - name: Run Robot Framework Testcases
        env:
          DOCKER_DGRAPH_VERSION: v21.03.0
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/Automation_workspace
          tree
          ls
          echo " ---- Running Dgraph Testcases ----"
          sudo robot -d results -v dgraph_docker_version:${{ env.DOCKER_DGRAPH_VERSION }} --loglevel TRACE:INFO --splitlog test_suites/dgraph/docker/dgraph_docker_2-node_suite.robot
          
      # Linting the Python code whenever there is a push in main branch
      - name: Python Pylint Github Action
        uses: fylein/python-pylint-github-action@v4
        if: always()
      
      
      # Getting Current time
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        if: always()
        id: current-time
        with:
          format: YYYYMMDD-HH_mm_ss
          utcOffset: "+05:30"
      
      # Publish Artifacts
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: automationArtifact_${{ steps.current-time.outputs.formattedTime }}
          path: |
            ${{ github.workspace }}/Automation_workspace/
            !${{ github.workspace }}/Automation_workspace/test_data
            !${{ github.workspace }}/Automation_workspace/doc
        
