# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          path: Automation_workspace
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8.7 # optional, default is 3.x
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64 # optional
          # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
          token: ${{ github.token }} # optional, default is ${{ github.token }}
          
      # Navigating to the directory and installing the requiremenets file
      - name: Install requirements for Dgraph
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/Automation_workspace/utilities
          ls -alh
          python3 env_setup.py -l Dgraph -c enabled
        
      - name: Install requirements for Slash
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/Automation_workspace/utilities
          ls -alh
          python3 env_setup.py -l Slash -c enabled
        
      # Download Dgraph Repo
      - name: Check out Dgraph repo
        uses: actions/checkout@master
        with:
          repository: dgraph-io/dgraph
          clean: false  
          path: dgraph_workspace  
        
          
      # Build Dgraph
      -  name: Build Dgraph
         run: |
           cd dgraph_workspace/dgraph
           make install
           sudo go build
           ls
           ./dgraph version
           sudo mv ./dgraph /bin
           dgraph version
         
      - name: Run Robot Framework Testcases
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/Automation_workspace
          tree
          cd test_suites/dgraph/Linux
          pwd
          robot -A dgraph_live_suite.robot
          
      # Linting the Python code whenever there is a push in main branch
      - name: Python Pylint Github Action
        uses: fylein/python-pylint-github-action@v4

        
